project_name: khaossweeper

builds:
  - id: "khaossweeper-linux"
    env: [CGO_ENABLED=1]
    goos:
      - linux
    goarch:
      - amd64
    binary: khaossweeper
  - id: "khaossweeper-darwin"
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
#      - arm64
    binary: khaossweeper
    ldflags:
      - -s -w

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

brews:
  - name: khaossweeper
    repository:
      owner: stenstromen
      name: homebrew-tap
    commit_author:
      name: stenstromen
    folder: Formula
    homepage: https://github.com/Stenstromen/khaossweeper
    description: KhaosSweeper, A thrilling Kubernetes minesweeper game.
