project_name: khaossweeper

builds:
  - id: "khaossweeper-amd64"
    env: 
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    binary: khaossweeper
    flags: 
      - -tags=netgo
    ldflags:
      - -s -w

  - id: "khaossweeper-darwin-arm64"
    env: 
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - darwin
    goarch:
      - arm64
    binary: khaossweeper
    flags: 
      - -tags=netgo
    ldflags:
      - -s -w

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

brews:
  - name: khaossweeper
    repository:
      owner: stenstromen
      name: homebrew-tap
    commit_author:
      name: stenstromen
    folder: Formula
    homepage: https://github.com/Stenstromen/khaossweeper
    description: KhaosSweeper, A thrilling Kubernetes minesweeper game.
